In [4]:
import pandas as pd

df=pd.read_csv('Dataset/job_salary.csv')

df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [6]:
# . Selecting Specific Columns
# How would you select just the job_title and Salary columns?

res=df[['job_title','salary']]
res.head()

            job_title  salary
0         AI Engineer  109413
1        Data Analyst   93764
2  Frontend Developer  148123
3    Business Analyst  189123
4     Product Manager  165069

In [9]:
# Filtering Rows:
# Can you show me all employees earning more than 90,000

res=df[df['salary']>90000]
res.head()

# Explanation: You create a boolean mask by writing a condition, then use it to filter the DataFrame.
# This is called boolean indexing.

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [15]:
# Adding a New Column
# How would you add a Bonus column that's 20% of the Salary?

df['Bonus']=df['salary']*0.20
df.tail()

# Explanation: You can create new columns by simply assigning values to a new column name.
# The calculation is applied element-wise.

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,Bonus
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791,25558.2
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593,30918.6
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988,15197.6
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467,18093.4
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084,26616.8

In [17]:
# Sorting Data
# Could you sort the employees by salary from highest to lowest?

sorted_data=df.sort_values('salary',ascending='False')
sorted_data

ValueError: For argument "ascending" expected type bool, received type str.